version: "3.8"
name: mixup-analysis-app

services:
  frontend:
    image: node:latest
    build:
      context: ./frontend
    depends_on:
      - backend
    environment:
      - ORIGIN=http://127.0.0.1:3000 # needs to be 127.0.0.1 and not localhost
    hostname: frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/frontend
    restart: always
  
  backend:
    image: python:latest
    build:
      context: ./backend
    hostname: backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/backend
    restart: on-failure