version: "3.8"
name: mixup-analysis-app

services:
  frontend:
    image: abhijeetkrishnan/mixup-analysis:frontend
    depends_on:
      - backend
    environment:
      - ORIGIN=http://127.0.0.1:3000 # needs to be host machine ip
    hostname: frontend
    ports:
      - "80:3000" # HTTP requests
      # - "443:3000" # HTTPS requests (TODO: setup security cert)
    volumes:
      - ./frontend:/frontend
    restart: always
  
  backend:
    image: abhijeetkrishnan/mixup-analysis:backend
    hostname: backend
    expose:
      - "8000"
    volumes:
      - ./backend:/backend
    restart: on-failure
